"""Command-line interface.

Every number quoted in the README is regenerated by these commands, so the
documentation can never drift from what the code produces.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

import pandas as pd
import typer

from quantedge.logging_config import configure_logging, get_logger

app = typer.Typer(help="QUANTEDGE — equity research & signal backtesting", no_args_is_help=True)
log = get_logger(__name__)

RESULTS = Path(__file__).resolve().parents[2] / "results"


def _setup(verbose: bool = True) -> None:
    configure_logging(logging.INFO if verbose else logging.WARNING)
    RESULTS.mkdir(parents=True, exist_ok=True)


@app.command()
def universe(years: int = typer.Option(6, help="Years of history to reconstruct")) -> None:
    """Rebuild point-in-time S&P 500 membership."""
    _setup()
    from quantedge.ingestion.pipeline import refresh_universe

    details = refresh_universe(years)
    typer.echo(json.dumps(details, indent=2))
    typer.secho(
        f"\n{details['ever_members']} ever-members "
        f"({details['removed_in_window']} removed during the window) — "
        "including removed names is what avoids survivorship bias.",
        fg=typer.colors.GREEN,
    )


@app.command()
def ingest(
    incremental: bool = typer.Option(False, help="Top up recent bars only"),
    lookback: int = typer.Option(7, help="Days to refetch when incremental"),
) -> None:
    """Fetch, clean and store OHLCV for the universe."""
    _setup()
    from quantedge.ingestion.pipeline import coverage_stats, ingest_incremental, ingest_prices

    details = ingest_incremental(lookback) if incremental else ingest_prices()
    typer.echo(json.dumps(details, indent=2, default=str)[:1500])
    typer.echo("\nCoverage:")
    typer.echo(json.dumps(coverage_stats(), indent=2, default=str))


@app.command()
def factors(
    horizons: str = typer.Option("1,5,10,21,42,63", help="Forward horizons for IC"),
) -> None:
    """Compute factor diagnostics (IC, decay, correlation) and save them."""
    _setup()
    from quantedge.factors.composite import CORE_FACTORS, get_factor
    from quantedge.factors.diagnostics import (
        cross_factor_correlation,
        factor_autocorrelation,
        ic_decay,
    )
    from quantedge.ingestion.telemetry import track_job
    from quantedge.strategy import load_panel

    parsed = tuple(int(h) for h in horizons.split(","))

    with track_job("factor_compute") as ctx:
        panel, _ = load_panel()
        signals = {name: get_factor(name).signal(panel) for name in CORE_FACTORS}

        out: dict = {"ic_decay": {}, "autocorrelation": {}}
        for name, sig in signals.items():
            decay = ic_decay(sig, panel, horizons=parsed, factor=name)
            out["ic_decay"][name] = decay.to_dict("records")
            out["autocorrelation"][name] = factor_autocorrelation(sig)

            headline = decay.iloc[0]
            typer.echo(
                f"{name:18s} IC(1d)={headline['mean_ic']:+.4f} "
                f"t={headline['t_stat']:+6.2f} p={headline['p_value']:.2e}"
            )

        out["cross_factor_correlation"] = cross_factor_correlation(signals).to_dict()
        ctx.rows_written = len(panel) * len(signals)
        ctx.tickers_processed = panel.shape[1]

    path = RESULTS / "factor_diagnostics.json"
    path.write_text(json.dumps(out, indent=2, default=str))
    typer.secho(f"\nSaved → {path}", fg=typer.colors.GREEN)


@app.command()
def snapshot() -> None:
    """Precompute factor scores into the database.

    The API serves these rows rather than rebuilding the panel per request,
    which is what lets a small instance run the Factor Explorer at all.
    """
    _setup()
    from quantedge.factors.snapshot import build_snapshot

    typer.echo(json.dumps(build_snapshot(), indent=2, default=str))


@app.command()
def backtest(
    walk_forward: bool = typer.Option(True, help="Walk-forward validate (recommended)"),
    save: bool = typer.Option(True, help="Persist the run to the database"),
) -> None:
    """Run the production strategy and report honest metrics."""
    _setup()
    from quantedge.backtest.naive import BacktestResult
    from quantedge.backtest.persistence import save_backtest_run
    from quantedge.ingestion.telemetry import track_job
    from quantedge.metrics.report import compare_is_oos, full_report
    from quantedge.metrics.trades import extract_trades, trade_statistics, turnover_statistics
    from quantedge.strategy import DEFAULT_SPEC, run_full_sample, run_walk_forward

    spec = DEFAULT_SPEC

    with track_job("backtest_nightly") as ctx:
        if walk_forward:
            wf, panel, benchmark = run_walk_forward(spec)
            if wf.oos_returns.empty:
                typer.secho("Walk-forward produced no out-of-sample data.", fg=typer.colors.RED)
                raise typer.Exit(1)

            report = compare_is_oos(
                wf.is_returns, wf.oos_returns, benchmark,
                n_trials=wf.n_configurations_tested,
            )
            equity = (1.0 + wf.oos_returns).cumprod() * 1_000_000
            result = BacktestResult(
                returns=wf.oos_returns, equity_curve=equity, weights=wf.oos_weights,
                turnover=wf.oos_turnover,
                costs=pd.Series(0.0, index=wf.oos_returns.index),
                gross_exposure=wf.oos_weights.abs().sum(axis=1),
                net_exposure=wf.oos_weights.sum(axis=1),
                engine="vectorized",
                metadata={
                    "config": spec.as_dict(), "costs": spec.cost_model().describe(),
                    "n_bars": len(wf.oos_returns), "n_tickers": panel.shape[1],
                },
            )
            metrics = dict(report["out_of_sample"])
            metrics["comparison"] = report["comparison"]
            metrics["in_sample"] = report["in_sample"]
            if not wf.oos_turnover.empty:
                metrics["turnover"] = turnover_statistics(wf.oos_turnover)
            trades = extract_trades(wf.oos_weights, panel)
            if not trades.empty:
                metrics["trades"] = trade_statistics(trades)

            _print_backtest(report, wf)
            name = f"{spec.name} (walk-forward OOS)"
        else:
            result, panel, benchmark, _ = run_full_sample(spec)
            metrics = full_report(
                result.returns, benchmark, turnover=result.turnover,
                n_trials=1, label="full_sample_in_sample",
            )
            wf = None
            typer.secho(
                "\nIN-SAMPLE ONLY — not a validated result.", fg=typer.colors.YELLOW
            )
            name = f"{spec.name} (full-sample, IN-SAMPLE)"

        ctx.rows_written = len(result.returns)
        ctx.tickers_processed = panel.shape[1]

        if save:
            run_id = save_backtest_run(
                name, result, metrics, prices=panel,
                walk_forward=wf, is_walk_forward=walk_forward,
            )
            ctx.details = {"run_id": run_id}
            typer.secho(f"\nSaved as run #{run_id}", fg=typer.colors.GREEN)

    path = RESULTS / ("walkforward.json" if walk_forward else "full_sample.json")
    path.write_text(json.dumps(metrics, indent=2, default=str))
    typer.echo(f"Metrics → {path}")


def _print_backtest(report: dict, wf) -> None:
    comparison = report["comparison"]
    oos = report["out_of_sample"]
    deflated = oos["deflated_sharpe"]

    typer.echo("\n" + "=" * 62)
    typer.secho("  WALK-FORWARD RESULT (out-of-sample)", bold=True)
    typer.echo("=" * 62)
    typer.echo(f"  Folds                 {len(wf.folds)}")
    typer.echo(f"  OOS observations      {len(wf.oos_returns)}")
    typer.echo(f"  In-sample Sharpe      {comparison['sharpe_is']:+.4f}")
    typer.secho(
        f"  Out-of-sample Sharpe  {comparison['sharpe_oos']:+.4f}",
        fg=typer.colors.GREEN, bold=True,
    )
    typer.echo(f"  Annualised return     {oos['returns']['annualized_return']:+.4f}")
    typer.echo(f"  Volatility            {oos['risk']['annualized_volatility']:.4f}")
    typer.echo(f"  Max drawdown          {oos['risk']['max_drawdown']:+.4f}")
    typer.echo(f"  Sortino / Calmar      {oos['risk_adjusted']['sortino_ratio']:.2f}"
               f" / {oos['risk_adjusted']['calmar_ratio']:.2f}")

    if "benchmark_relative" in oos:
        br = oos["benchmark_relative"]
        typer.echo(f"  Information ratio     {br['information_ratio']:+.4f}")
        typer.echo(f"  Benchmark Sharpe      {br['benchmark_sharpe']:.4f}")

    if "attribution" in oos:
        ab = oos["attribution"]
        typer.echo(f"  Beta / alpha t-stat   {ab['beta']:+.2f} / {ab['alpha_t_stat']:+.2f}")

    typer.echo("-" * 62)
    typer.secho("  Multiple-testing check", bold=True)
    typer.echo(f"  Configurations tested {deflated['n_trials']}")
    typer.echo(f"  Deflated Sharpe       {deflated['deflated_sharpe']:.4f}")
    typer.secho(f"  {deflated['interpretation']}", fg=typer.colors.YELLOW)
    typer.echo("=" * 62)


@app.command()
def benchmark(
    repeats: int = typer.Option(3, help="Best-of-N timing runs"),
    scaling: bool = typer.Option(True, help="Also measure scaling with universe size"),
) -> None:
    """Measure the vectorized engine against the naive loop."""
    _setup(verbose=False)
    from quantedge.backtest.benchmark import compare_engines, scaling_benchmark
    from quantedge.strategy import DEFAULT_SPEC, load_panel, score_builder

    spec = DEFAULT_SPEC
    panel, _ = load_panel()
    scores = score_builder(panel, {"weights": spec.factor_weights, "orient": {"volatility": -1}})

    result = compare_engines(
        panel, scores, config=spec.portfolio_config(),
        cost_model=spec.cost_model(), repeats=repeats,
    )
    typer.echo(result.summary())

    if not result.results_match:
        typer.secho(
            "PARITY FAILED — the speedup figure is meaningless until the "
            "engines agree.", fg=typer.colors.RED, bold=True,
        )
        raise typer.Exit(1)

    payload = {"headline": result.as_dict()}

    if scaling:
        table = scaling_benchmark(
            panel, scores, ticker_counts=(50, 100, 250, 500, panel.shape[1]),
            config=spec.portfolio_config(), repeats=repeats,
        )
        typer.echo(table.to_string(index=False))
        payload["scaling"] = table.to_dict("records")

    path = RESULTS / "benchmark.json"
    path.write_text(json.dumps(payload, indent=2, default=str))
    typer.secho(f"\nSaved → {path}", fg=typer.colors.GREEN)


@app.command()
def signals(top: int = typer.Option(20, help="How many names to show")) -> None:
    """Print the strategy's current ranking."""
    _setup(verbose=False)
    from quantedge.strategy import current_signals

    df = current_signals(top_n=top)
    typer.echo(df.to_string(index=False) if not df.empty else "No signals available.")


@app.command()
def status() -> None:
    """Show pipeline health and data coverage."""
    _setup(verbose=False)
    from quantedge.ingestion.pipeline import coverage_stats
    from quantedge.ingestion.telemetry import compute_uptime, recent_runs

    typer.echo(json.dumps(
        {
            "coverage": coverage_stats(),
            "uptime": compute_uptime(days=30),
            "recent_runs": recent_runs(5),
        },
        indent=2, default=str,
    ))


@app.command()
def schedule(
    ingest_hour: int = typer.Option(22, help="UTC hour for the daily ingest"),
) -> None:
    """Run the scheduler in the foreground."""
    _setup()
    from quantedge.ingestion.scheduler import run_scheduler

    run_scheduler(ingest_hour=ingest_hour)


if __name__ == "__main__":
    app()
