"""initial schema

Revision ID: 19ab091b8679
Revises: 
Create Date: 2026-07-28 22:49:33.882259
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '19ab091b8679'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_request_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('endpoint', sa.String(length=128), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_request_log_created_at'), 'api_request_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_request_log_endpoint'), 'api_request_log', ['endpoint'], unique=False)
    op.create_table('app_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_logs_created_at'), 'app_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_app_logs_level'), 'app_logs', ['level'], unique=False)
    op.create_index(op.f('ix_app_logs_source'), 'app_logs', ['source'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('engine_type', sa.String(length=16), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_walk_forward', sa.Boolean(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('sharpe_oos', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('runtime_ms', sa.Float(), nullable=True),
    sa.Column('n_trades', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_created_at'), 'backtest_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_backtest_runs_sharpe'), 'backtest_runs', ['sharpe'], unique=False)
    op.create_table('factor_ic',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('factor_name', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('ic', sa.Float(), nullable=True),
    sa.Column('rank_ic', sa.Float(), nullable=True),
    sa.Column('n_obs', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factor_name', 'date', 'horizon_days', name='uq_ic')
    )
    op.create_index(op.f('ix_factor_ic_date'), 'factor_ic', ['date'], unique=False)
    op.create_index(op.f('ix_factor_ic_factor_name'), 'factor_ic', ['factor_name'], unique=False)
    op.create_table('factor_values',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('factor_name', sa.String(length=32), nullable=False),
    sa.Column('raw_value', sa.Float(), nullable=True),
    sa.Column('zscore', sa.Float(), nullable=True),
    sa.Column('rank_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ticker', 'date', 'factor_name')
    )
    op.create_index('ix_factor_date_name', 'factor_values', ['date', 'factor_name'], unique=False)
    op.create_table('job_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('rows_written', sa.Integer(), nullable=False),
    sa.Column('bytes_processed', sa.BigInteger(), nullable=False),
    sa.Column('tickers_processed', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_runs_job_name'), 'job_runs', ['job_name'], unique=False)
    op.create_index(op.f('ix_job_runs_started_at'), 'job_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_job_runs_status'), 'job_runs', ['status'], unique=False)
    op.create_table('ohlcv_clean',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('dollar_volume', sa.Float(), nullable=True),
    sa.Column('returns', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    op.create_index('ix_clean_date', 'ohlcv_clean', ['date'], unique=False)
    op.create_index('ix_clean_ticker_date', 'ohlcv_clean', ['ticker', 'date'], unique=False)
    op.create_table('ohlcv_raw',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', 'source', name='uq_raw_ticker_date_source')
    )
    op.create_index(op.f('ix_ohlcv_raw_ticker'), 'ohlcv_raw', ['ticker'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_created_at'), 'risk_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_events_event_type'), 'risk_events', ['event_type'], unique=False)
    op.create_table('securities',
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_date', sa.Date(), nullable=True),
    sa.Column('last_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index(op.f('ix_securities_sector'), 'securities', ['sector'], unique=False)
    op.create_table('universe_membership',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('index_name', sa.String(length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_membership_lookup', 'universe_membership', ['index_name', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_universe_membership_index_name'), 'universe_membership', ['index_name'], unique=False)
    op.create_index(op.f('ix_universe_membership_ticker'), 'universe_membership', ['ticker'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('returns', sa.Float(), nullable=True),
    sa.Column('drawdown', sa.Float(), nullable=True),
    sa.Column('gross_exposure', sa.Float(), nullable=True),
    sa.Column('net_exposure', sa.Float(), nullable=True),
    sa.Column('n_positions', sa.Integer(), nullable=True),
    sa.Column('positions', sa.JSON(), nullable=True),
    sa.Column('is_oos', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_snapshots_date'), 'portfolio_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_run_id'), 'portfolio_snapshots', ['run_id'], unique=False)
    op.create_index('ix_snapshot_run_date', 'portfolio_snapshots', ['run_id', 'date'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('pnl_abs', sa.Float(), nullable=True),
    sa.Column('costs', sa.Float(), nullable=True),
    sa.Column('holding_days', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_run_pnl', 'trades', ['run_id', 'pnl_pct'], unique=False)
    op.create_index(op.f('ix_trades_entry_date'), 'trades', ['entry_date'], unique=False)
    op.create_index(op.f('ix_trades_run_id'), 'trades', ['run_id'], unique=False)
    op.create_index(op.f('ix_trades_ticker'), 'trades', ['ticker'], unique=False)
    op.create_table('walk_forward_folds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('fold_index', sa.Integer(), nullable=False),
    sa.Column('train_start', sa.Date(), nullable=False),
    sa.Column('train_end', sa.Date(), nullable=False),
    sa.Column('test_start', sa.Date(), nullable=False),
    sa.Column('test_end', sa.Date(), nullable=False),
    sa.Column('sharpe_is', sa.Float(), nullable=True),
    sa.Column('sharpe_oos', sa.Float(), nullable=True),
    sa.Column('return_oos', sa.Float(), nullable=True),
    sa.Column('max_drawdown_oos', sa.Float(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_walk_forward_folds_run_id'), 'walk_forward_folds', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_walk_forward_folds_run_id'), table_name='walk_forward_folds')
    op.drop_table('walk_forward_folds')
    op.drop_index(op.f('ix_trades_ticker'), table_name='trades')
    op.drop_index(op.f('ix_trades_run_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_entry_date'), table_name='trades')
    op.drop_index('ix_trade_run_pnl', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_snapshot_run_date', table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_run_id'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_date'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_universe_membership_ticker'), table_name='universe_membership')
    op.drop_index(op.f('ix_universe_membership_index_name'), table_name='universe_membership')
    op.drop_index('ix_membership_lookup', table_name='universe_membership')
    op.drop_table('universe_membership')
    op.drop_index(op.f('ix_securities_sector'), table_name='securities')
    op.drop_table('securities')
    op.drop_index(op.f('ix_risk_events_event_type'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_created_at'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_ohlcv_raw_ticker'), table_name='ohlcv_raw')
    op.drop_table('ohlcv_raw')
    op.drop_index('ix_clean_ticker_date', table_name='ohlcv_clean')
    op.drop_index('ix_clean_date', table_name='ohlcv_clean')
    op.drop_table('ohlcv_clean')
    op.drop_index(op.f('ix_job_runs_status'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_started_at'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_job_name'), table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index('ix_factor_date_name', table_name='factor_values')
    op.drop_table('factor_values')
    op.drop_index(op.f('ix_factor_ic_factor_name'), table_name='factor_ic')
    op.drop_index(op.f('ix_factor_ic_date'), table_name='factor_ic')
    op.drop_table('factor_ic')
    op.drop_index(op.f('ix_backtest_runs_sharpe'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_created_at'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_app_logs_source'), table_name='app_logs')
    op.drop_index(op.f('ix_app_logs_level'), table_name='app_logs')
    op.drop_index(op.f('ix_app_logs_created_at'), table_name='app_logs')
    op.drop_table('app_logs')
    op.drop_index(op.f('ix_api_request_log_endpoint'), table_name='api_request_log')
    op.drop_index(op.f('ix_api_request_log_created_at'), table_name='api_request_log')
    op.drop_table('api_request_log')
    # ### end Alembic commands ###
