"""factor snapshots

Revision ID: 4c62c0f71f78
Revises: d38c0a88385a
Create Date: 2026-07-29 16:02:06.137274
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '4c62c0f71f78'
down_revision: str | None = 'd38c0a88385a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factor_diagnostics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factor_diagnostics_as_of'), 'factor_diagnostics', ['as_of'], unique=False)
    op.create_index(op.f('ix_factor_diagnostics_kind'), 'factor_diagnostics', ['kind'], unique=False)
    op.create_table('factor_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('bias', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('as_of', 'ticker', name='uq_factor_snapshot')
    )
    op.create_index('ix_factor_snapshot_as_of', 'factor_snapshots', ['as_of', 'composite_score'], unique=False)
    op.create_index(op.f('ix_factor_snapshots_as_of'), 'factor_snapshots', ['as_of'], unique=False)
    op.create_index(op.f('ix_factor_snapshots_ticker'), 'factor_snapshots', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_factor_snapshots_ticker'), table_name='factor_snapshots')
    op.drop_index(op.f('ix_factor_snapshots_as_of'), table_name='factor_snapshots')
    op.drop_index('ix_factor_snapshot_as_of', table_name='factor_snapshots')
    op.drop_table('factor_snapshots')
    op.drop_index(op.f('ix_factor_diagnostics_kind'), table_name='factor_diagnostics')
    op.drop_index(op.f('ix_factor_diagnostics_as_of'), table_name='factor_diagnostics')
    op.drop_table('factor_diagnostics')
    # ### end Alembic commands ###
